#+title: DAVE3625 - Readme
#+author: Kenneth R. Eikrehagen & Sindre B. Øvstegård
#+description: Readme for assignments in DAVE3625 at OsloMet. Emails to authors is s331475@oslomet.no (Kenneth) & s318337@oslomet.no (Sindre).

* Notes

** Participants
   * Kenneth Ramos Eikrehagen (s331475@oslomet.no)
   * Sindre Bergsvik Øvstegård (s318337@oslomet.no)

* Assignment 1
  Assignment1.ipynb is our delivery file, testing.ipynb file is for testing the data-set and getting to know pandas better

* Assignment 2
** Task 1 - Regression <2020-10-21>
   Task 1 was chosen for the assignment. Based on the data presented in "NAS.csv", a linear regression model was implemeted.
   Also there is no need for labelling the data as discrete classes, when the object is to predict "continuous" values.

* Final assignment
2) Risk assessment: Describe a software which currently uses AI (take any example).
You should briefly describe the context of the application, method of A.I used and current/expected A.I outcomes.
Once the application is well defined, provide an account of relevant risks and collateral consequences related to using A.I.

** Possible topics:
-  Facerecognition (CC TV)
-  Autonomous cars

** Some usefull links:
EV: [[engineeringvillage][https://www.engineeringvillage.com/search/quick.url?SEARCHID=a6e0bdd0f8a54971a509cc4907c7347e&COUNT=1&usageOrigin=&usageZone=]]

** Description of Assignment
Description of the task
Write a report on one of the following topics:

-  1. Implementation use-case: You describe a novel problem, you describe what data is available, and you describe how to solve the problem using AI, by providing reasoning. It is critical that the methodology chosen is adequate to the problem, the data, and the desired outcome.

-  2. Risk assessment: Describe a software which currently uses AI (take any example). You should briefly describe the context of the application, method of A.I used and current/expected A.I outcomes. Once the application is well defined, provide an account of relevant risks and collateral consequences related to using A.I.

-  3. In-depth explanation: Choose one algorithm in Artificial Intelligence. Explain it in detail and provide two examples of applications that are not cited in any of the slides or reference material.

Guide:
Use examples if you can, showing step by step how the system works/will work is a good way to demonstrate your knowledge. Below you will find more detailed questions to consider when considering the project. You do not need to answer all of these in your report but use them as a guideline and as a way to test your knowledge.

Introduction: Provide the context for the problem: What is the problem? When and where does it happen? Who is affected by it? What are the likely causes of the problem (if known)? What is needed to solve the problem? What is the expected consequence if the problem is solved and if the problem keeps unsolved? Is it a business opportunity? if so, what is the business model/theory?

Resources: Given what you know. Describe what is the data available and how to get access to it. Is it structured, unstructured, or mixed? Is it labeled data? if you need to label the data, how would you label it and what kind of person should label it (explain why). How much data do you have? Is it enough? How would you know if it is enough or not?
If you need to collect the data, how would you collect it? What are the sources for the data? What problems do you anticipate? Do you have to pay for the data? if so, how much? If you do not know, where can you start looking for it?
How reliable, complete, and clean are your data? Is it likely to have missing data points, mistakes, or inconsistencies? What is that you think that can be done to solve these problems?
Do you need to perform any feature selection or engineering?

Method: What kind of machine learning problem are you trying to solve? Classification, Regression, Clustering, Association, or Dimensional reduction?
In your professional opinion, what are the most relevant features of your data set for your problem? What are the features that are completely irrelevant? Provide reasons for your judgment.
How would test if your model is doing what you expect out of it? Provide reasons for your testing choice.
How would you update your model? How often? What resources you have for that, and what problems are in your way?