#+author: Sindre & Kenneth
#+title: Links and references
#+description: Links and references to final report in DAVE3625 year 2020.

* Assignemtn description
** Task
2. Risk assessment: Describe a software which currently uses AI (take any example). You should briefly describe the context of the application,
method of A.I used and current/expected A.I outcomes. Once the application is well defined,
provide an account of relevant risks and collateral consequences related to using A.I.
** Additional
Use examples if you can, showing step by step how the system works/will work is a good way to demonstrate your knowledge. Below you will find more detailed questions to consider when considering the project. You do not need to answer all of these in your report but use them as a guideline and as a way to test your knowledge.

Introduction: Provide the context for the problem: What is the problem? When and where does it happen? Who is affected by it? What are the likely causes of the problem (if known)? What is needed to solve the problem? What is the expected consequence if the problem is solved and if the problem keeps unsolved? Is it a business opportunity? if so, what is the business model/theory?

Resources: Given what you know. Describe what is the data available and how to get access to it. Is it structured, unstructured, or mixed? Is it labeled data? if you need to label the data, how would you label it and what kind of person should label it (explain why). How much data do you have? Is it enough? How would you know if it is enough or not?
If you need to collect the data, how would you collect it? What are the sources for the data? What problems do you anticipate? Do you have to pay for the data? if so, how much? If you do not know, where can you start looking for it?
How reliable, complete, and clean are your data? Is it likely to have missing data points, mistakes, or inconsistencies? What is that you think that can be done to solve these problems?
Do you need to perform any feature selection or engineering?

Method: What kind of machine learning problem are you trying to solve? Classification, Regression, Clustering, Association, or Dimensional reduction?
In your professional opinion, what are the most relevant features of your data set for your problem? What are the features that are completely irrelevant? Provide reasons for your judgment.
How would test if your model is doing what you expect out of it? Provide reasons for your testing choice.
How would you update your model? How often? What resources you have for that, and what problems are in your way?

* Links:
** Example
Example how to use link -> [[url goes here][name that is displayed]]
** towardsdatascience
[[https://towardsdatascience.com/ai-and-the-vehicle-went-autonomous-e176c73239c6][Forskjellige algorithmer i selvkjørende biler]]
** IEEE articles
- [[https://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=5940562][Towards Fully Autonomous Driving: Systems and Algorithms]]
- [[https://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=8457076&tag=1][Autonomous Cars: Research Results, Issues, and Future Challenges]]
** IBM articles
[[https://www.ibm.com/cloud/blog/ai-vs-machine-learning-vs-deep-learning-vs-neural-networks][AI vs ML vs DL vs NN]]
